### PR TITLE
Raw download

### PR DESCRIPTION
**Pull request by psteinb**
Here is the code. 

Note: I am not sure how to run `testthat.R` with my new code. I added a new unit test for my editions. `.travis.yml` didn't yield any help on this. The `testthat` docs hinted at yet another package to use. :/

### CODE REVIEW

**Comment by nevrome** [comment]
Maybe take a quick look at [`devtools::document()`](http://r-pkgs.had.co.nz/man.html#man-workflow) and [`devtools::test()`](http://r-pkgs.had.co.nz/tests.html#test-workflow) .

The code looks fine.

**Comment by psteinb** [comment]
indeed I forgot to add documentation for the new function argument

**Comment by psteinb** [comment]
I ran 
```
$ Rscript -e 'library(devtools);devtools::document()'
```
and
```
$ Rscript -e 'library(devtools);devtools::test()'
```
without any warnings. But the travis build still fails.

**Comment by psteinb** [comment]
ready when you are!

**Pull request merged**
